name: myhome_weekly

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 0'

jobs:
  autoscrape:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          R -e 'install.packages("jsonlite")'
          R -e 'install.packages("httr2")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("tidyr")'
      
      - name: Scrape
        run: Rscript weekly_scraper_script.R
      
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update data: ${timestamp}" || exit 0
          git push
